{{- range .Values.application.repositories }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $.Values.argocd.project }}-{{ base .repoURL | trimSuffix ".git" }}-{{ sha1sum .repoURL | trunc 4 }}
  namespace: {{ $.Values.argocd.namespace }}
  labels:
    app.kubernetes.io/managed-by: dso-console
    {{- if $.Values.commonLabels -}}
    {{- $.Values.commonLabels | toYaml | nindent 4 }}
    {{- end }}
  finalizers:
    # foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $.Values.argocd.project }}-app
  source: 
    repoURL: {{ .repoURL }}
    targetRevision:  {{ .targetRevision }}
    path: {{ .path }}
    {{- if len .valueFiles }}
    helm:
      valueFiles: {{ .valueFiles | toJson }}
    {{- end }}
  destination:
    name: {{ $.Values.application.destination.name }}
    namespace: {{ $.Values.application.destination.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
{{- end }}
