apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    app.kubernetes.io/managed-by: dso-console
    {{- if $.Values.commonLabels -}}
    {{- $.Values.commonLabels | toYaml | nindent 4 }}
    {{- end }}
  name: {{ .Values.argocd.project }}-env
  namespace: {{ .Values.argocd.namespace }}
spec:
  destinations:
  - name: {{ .Values.application.destination.name }}
    namespace: {{ .Values.application.destination.namespace }}
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
    - https://github.com/cloud-pi-native/helm-charts.git
    - {{ .Values.environment.valueFileRepository }}
    - {{ .Values.application.sourceReposPrefix }}/*

