{{- if and .Values.cnpg.enabled .Values.cnpg.backup.enabled .Values.cnpg.backup.s3Credentials.create }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.cnpg.backup.s3Credentials.secretName | default (printf "%s-%s" "pg-cluster" (include "cpnConsole.fullname" .)) }}
  labels:
    {{- include "cpnConsole.common.labels" . | nindent 4 }}
data:
  {{ .Values.cnpg.backup.s3Credentials.accessKeyId.key | indent 2 -}}: {{ .Values.cnpg.backup.s3Credentials.accessKeyId.value | b64enc }}
  {{ .Values.cnpg.backup.s3Credentials.secretAccessKey.key | indent 2 -}}: {{ .Values.cnpg.backup.s3Credentials.secretAccessKey.value | b64enc }}
{{- end -}}
