{{- if and .Values.cnpg.enabled .Values.cnpg.backup.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ .Values.cnpg.nameOverride | default (printf "%s-%s" "pg-cluster" (include "cpnConsole.fullname" .)) }}
  labels:
    {{- include "cpnConsole.common.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cnpg.backup.cron }}
  backupOwnerReference: self
  cluster:
    name: {{ .Values.cnpg.nameOverride | default (printf "%s-%s" "pg-cluster" (include "cpnConsole.fullname" .)) }}
{{- end }}