{{- if and .Values.cnpg.enabled .Values.cnpg.exposed }}
apiVersion: v1
kind: Service
metadata:
  name: {{ (printf "%s-%s" .Values.cnpg.nameOverride "rw-nodeport") | default (printf "%s-%s" (include "cpnConsole.fullname" .) "pg-cluster") }}
  labels:
    {{- include "cpnConsole.common.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.cnpg.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    nodePort: {{ .Values.cnpg.nodePort }}
  selector:
    cnpg.io/cluster: {{ .Values.cnpg.nameOverride | default (printf "%s-%s" (include "cpnConsole.fullname" .) "pg-cluster") }}
    role: primary
  type: NodePort
{{- end }}