apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.application.destination.namespace }}
  labels:
    app.kubernetes.io/managed-by: dso-console
    {{- if .Values.commonLabels }}
    {{- .Values.commonLabels | toYaml | nindent 4 }}
    {{- end }}
