---
apiVersion: v2
name: dso-argocd
type: application
version: 1.2.1
appVersion: 2.12.3
dependencies:
  - name: argo-cd
    repository: https://argoproj.github.io/argo-helm
    version: 7.5.2
  - name: vault-secrets-operator
    repository: https://helm.releases.hashicorp.com
    version: 0.8.1
    condition: vso.install
maintainers:
  - name: this-is-tobi
    email: thibault.colin@interieur.gouv.fr
    url: https://this-is-tobi.com
