apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cpnConsole.fullname" . }}-server
  labels: {{- include "cpnConsole.server.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  - user.openshift.io
  - rbac.authorization.k8s.io
  - argoproj.io
  {{- if .Values.features.vaultSecrets.enabled }}
  - secrets.hashicorp.com
  {{- end }}
  resources:
  - '*'
  verbs:
  - '*'
