apiVersion: v2
name: cpn-cnpg
description: A Helm Chart to deploy easily a CNPG cluster
type: application
version: 1.0.0
appVersion: 1.0.0
keywords: []
home: https://cloud-pi-native.fr
sources:
  - https://github.com/cloud-pi-native/helm-charts
deprecated: false
annotations: {}
maintainers:
  - name: this-is-tobi
    email: thibault.colin@interieur.gouv.fr
    url: https://this-is-tobi.com
