apiVersion: v1
kind: Service
metadata:
  name: {{ include "observatorium.resourceName" (dict "ctx" $ "component" "api") }}
  labels:
    {{- include "observatorium.labels" (dict "ctx" $ "component" "api") | nindent 4 }}
spec:
  ports:
  - appProtocol: h2c
    name: grpc-public
    port: 8090
    targetPort: 8090
  - appProtocol: http
    name: internal
    port: 8081
    targetPort: 8081
  - appProtocol: http
    name: public
    port: 8080
    targetPort: 8080
  selector:
    {{- include "observatorium.selectorLabels" (dict "ctx" $ "component" "api") | nindent 4 }}
