{{- if .Values.api.config.customCA.enabled }}
apiVersion: v1
kind: Secret
metadata:
  labels:
     {{- include "observatorium.labels" (dict "ctx" $ "component" "api" ) | nindent 4 }}
  name: {{ include "observatorium.resourceName" (dict "ctx" $ "component" "api") }}-crt
data:
  ca.crt: {{ .Values.api.config.customCA.cert }}
{{- end }}