{{- if .Values.rate_limiter.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "observatorium.resourceName" (dict "ctx" . "component" "rate-limiter") }}
  labels:
    {{- include "observatorium.labels" (dict "ctx" . "component" "rate-limiter") | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: observatorium-gubernator
subjects:
- kind: ServiceAccount
  name: observatorium-gubernator
  namespace: infra-loki
{{- end }}