{{- if .Values.rate_limiter.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "observatorium.resourceName" (dict "ctx" . "component" "rate-limiter") }}
  labels:
    {{- include "observatorium.labels" (dict "ctx" . "component" "rate-limiter") | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - list
  - watch
  - get
{{- end }}