{{- if and (eq .Values.mode "primary") .Values.initSecret.enabled }}
apiVersion: v1
data:
  username: {{ .Values.initSecret.username }} 
  password: {{ .Values.initSecret.password }} 
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/remove-missing: 'true'
  name: {{ (printf "%s-%s" .Values.nameOverride "db") | default (printf "%s-%s-%s" (include "cpnCnpg.fullname" .) "pg-cluster" "db") }}
type: kubernetes.io/basic-auth
{{- end }}
