{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Values.nameOverride | default (printf "%s-%s" "pg-cluster" (include "cpnCnpg.fullname" .)) }}
  labels:
    {{- include "cpnCnpg.labels" . | nindent 4 }}
    {{- with .Values.monitoring.podMonitorAdditionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end}}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "cpnCnpg.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: metrics
      {{- with .Values.monitoring.podMonitorMetricRelabelings }}
      metricRelabelings:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.monitoring.podMonitorRelabelings }}
      relabelings:
      {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}
