{{- if and .Values.pooler.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pooler-{{ .Values.nameOverride | default (printf "%s-%s" "pg-cluster" (include "cpnCnpg.fullname" .)) }}
spec:
  cluster:
    name: {{ .Values.nameOverride | default (printf "%s-%s" "pg-cluster" (include "cpnCnpg.fullname" .)) }}
  instances: {{ .Values.pooler.instances }}
  type: rw
  pgbouncer:
    poolMode: {{ .Values.pooler.poolMode }}
    parameters:
      {{- .Values.pooler.parameters | toYaml | nindent 6 }}
{{- end -}}
